# Header
menu:
  Home: /
  Archives: /archives
  About: /about

link:
  Github: https://github.com/buppt
  CSDN: http://blog.csdn.net/buppt
  weibo: http://weibo.com/buppt

# Author
author: buppt
avatar: /img/photohead.png
name: 【意涵团·团员】BUPPT
introduce: 北京邮电大学2017研一


